# sudo docker-compose up -d
version: "3.9"
services:
  php:
    #image: php:8.1-fpm
    build: './etc/infrastructure/php'
    container_name: crm_php
    volumes:
    - ./etc/.bashrc:/root/.bashrc
    - .:/var/www/crm/
    - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d/
    working_dir: /var/www/crm/
    links:
    - db
    - cache
  web:
    #image: nginx:stable
    build: './etc/infrastructure/nginx'
    container_name: crm_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./etc/.bashrc:/root/.bashrc
    - .:/var/www/crm/
    - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./etc/infrastructure/nginx/ssl/:/etc/ssl/
    - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d/
    links:
    - cache
    - db
    - php
    depends_on:
    - php
  cache:
    image: redis
    container_name: crm_cache
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - ./etc/infrastructure/redis/redis.conf:/etc/redis/redis.conf
  db:
    image: mariadb:latest
    container_name: crm_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}  # Add this line
volumes:
  db_data:
